version: 1.0.{build}
image:
- Visual Studio 2019
- Ubuntu2004
  #- Ubuntu1804
build_script:
- cmd: msbuild "./vc/vc14_fceux.sln"
- cmd: ./vc/archive.bat
- cmd: appveyor PushArtifact  ./vc/fceux.zip
- sh: ./pipelines/linux_build.sh
